### ISSUE TITLE
Support Ubuntu Host

### ISSUE THREAD

**Issue by tobru** [andrekeller/archvyrt#2]
I just checked the scripts and it looks like it doesn't need much work the support Ubuntu as a virtualization host:

**arch-chroot**
https://github.com/andrekeller/archvyrt/blob/master/archvyrt/provisioner/ubuntu.py#L23
We need to somehow bring this to Ubuntu, f.e. by creating a debian package of https://projects.archlinux.org/arch-install-scripts.git

**paths**
https://github.com/andrekeller/archvyrt/blob/master/archvyrt/provisioner/ubuntu.py#L34
This one is at `/usr/sbin/debootstrap` on Ubuntu

**parameters**
https://github.com/andrekeller/archvyrt/blob/master/archvyrt/provisioner/ubuntu.py#L35
Make this configurable to support debootstrapping different versions

**mirror**
https://github.com/andrekeller/archvyrt/blob/master/archvyrt/provisioner/ubuntu.py#L37
de.?

**bootstrapping arch**
Could be done with https://github.com/tokland/arch-bootstrap

**Comment by andrekeller** [comment]
**arch-chroot**
agreed, should be rather easy as this is just bash after all

**paths**
this is something that could be handled by the package. making this configurable does not really make sense imho, as this is host specific.

**parameters**
this is also an easy one, f.e. by introducing an guesttype_options parameter in vmdefinitions file

**mirror**
goes into parameters as-well. during testing my local .ch mirror had hash-sum mismatches, so I switched to .de.


will have a look into this and probably provide a testing package on a ppa somewhere

**Comment by andrekeller** [comment]
as to bootstrapping arch, its not a priority for me. Feel free to contribute :-)

**Comment by tobru** [comment]
> as to bootstrapping arch, its not a priority for me. Feel free to contribute :-)

will do :+1:

**Comment by andrekeller** [comment]
basic version is working on ubuntu 14.04. just make sure you have hugepages enabled, and nbd module loaded with support for partitions (see the archlinux docs). Also an openvswitch bridge should be ready.

packages for archvyrt and dependencies are in: https://launchpad.net/~0x2a/+archive/ubuntu/archvyrt

add the ppa & install python3-archvyrt and you are good to go.

there is still a bug, that stopping the ssh daemon in the chroot will also stop the ssh daemon on the host, probably because of reasons :-)

please test, PR for updated documentation welcome :-)

**Comment by andrekeller** [comment]
> there is still a bug, that stopping the ssh daemon in the chroot will also stop the ssh daemon on the
> host, probably because of reasons :-)

fixed in 07372d1e031d988e15d8f0849c3ea4dec14c5124

**Comment by andrekeller** [comment]
This has been implemented for quite some time now, and recently has been adjusted for ubuntu 16.04 support.
